import{a as L,S as v,i as c}from"./assets/vendor-hwdYKDic.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const w="46181827-8f08ac25b58b643ff6d61f160",S="https://pixabay.com/api/";async function m(e,r=1,a=40){try{return(await L.get(S,{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:a}})).data}catch(s){throw console.error("Помилка запиту до Pixabay API:",s),s}}function p(e){const r=document.querySelector(".gallery"),a=e.map(({webformatURL:s,largeImageURL:t,tags:o,likes:n,views:h,comments:g,downloads:b})=>`
      <a class="gallery__item" href="${t}">
        <div class="photo-card">
          <img src="${s}" alt="${o}" loading="lazy" />
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${n}</p>
            <p class="info-item"><b>Views:</b> ${h}</p>
            <p class="info-item"><b>Comments:</b> ${g}</p>
            <p class="info-item"><b>Downloads:</b> ${b}</p>
          </div>
        </div>
      </a>
    `).join("");r.insertAdjacentHTML("beforeend",a)}function q(){const e=document.querySelector(".gallery");e.innerHTML=""}let i=1,l="";const P=document.querySelector("#search-form"),d=document.querySelector(".load-more"),u=document.querySelector(".loader-wrapper");document.querySelector(".gallery");let y=new v(".gallery a");const f=e=>{e?u.classList.remove("is-hidden"):u.classList.add("is-hidden")},$=()=>{const e=document.querySelector(".gallery .photo-card");if(e){const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}};P.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.currentTarget.elements.searchQuery.value.trim(),i=1,q(),d.classList.add("is-hidden"),!l){c.warning({title:"Попередження",message:"Будь ласка, введіть запит для пошуку."});return}f(!0);try{const r=await m(l,i);if(r.hits.length===0){c.info({title:"Нічого не знайдено",message:"На жаль, за вашим запитом зображень не знайдено. Спробуйте ще раз!"});return}p(r.hits),y.refresh(),r.totalHits>i*40&&d.classList.remove("is-hidden")}catch{c.error({title:"Помилка",message:"Сталася помилка при завантаженні зображень. Спробуйте пізніше."})}finally{f(!1)}});d.addEventListener("click",async()=>{i+=1,f(!0);try{const e=await m(l,i);p(e.hits),y.refresh(),$(),e.totalHits<=i*40&&(d.classList.add("is-hidden"),c.info({title:"Кінець результатів",message:"We're sorry, but you've reached the end of search results."}))}catch{c.error({title:"Помилка",message:"Сталася помилка при завантаженні додаткових зображень."})}finally{f(!1)}});
//# sourceMappingURL=index.js.map
